### ISSUE TITLE
beta版的数个问题

### ISSUE THREAD

**Issue by Mikachu2333** [amzxyz/rime-wanxiang#117]
1. charset文件已被删除但是仍被引用 (<.\wanxiang_pro.schema.yaml#L32>) 等
2.  custom文件夹内的教程错误（ <.\custom\wanxiang_pro.custom.yaml#L4> <.\custom\wanxiang_pro.custom.yaml#L5>）处应为 `wanxiang_pro.schema:/小鹤双拼` 与`- wanxiang_pro.schema:/直接辅助`
3. 其他问题待测

---
更新，上述问题已于 [96830f3](https://github.com/amzxyz/rime_wanxiang/commit/96830f32618d22c0a2315427784ec7728a3ebed9) 解决

**Comment by Mikachu2333** [comment]
4. `translator/packs/+:` 不支持在指定目录下的字典（我有4个字典需要添加，存在相关关系但名称不同，全都放在根目录下难以管理并且十分不便）
例如我把自有字典统一放在了根目录下的 `custom_dicts` 文件夹中

**Comment by Mikachu2333** [comment]
5. 能否提供一个方法使我能将候选选项设置为8个？（我无需音调辅助，并且注意到文档中没有给出功能的关闭方法）

**Comment by Mikachu2333** [comment]
更新，1、2、3已解决

**Comment by amzxyz** [comment]
> 5. 能否提供一个方法使我能将候选选项设置为8个？（我无需音调辅助，并且注意到文档中没有给出功能的关闭方法）

通过patch删除7890 >> speller/alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA7890`/

**Comment by amzxyz** [comment]
> 4. `translator/packs/+:` 不支持在指定目录下的字典（我有4个字典需要添加，存在相关关系但名称不同，全都放在根目录下难以管理并且十分不便）
>    例如我把自有字典统一放在了根目录下的 `custom_dicts` 文件夹中

这个是rime的设定，想要那样只能与文件夹引入dict的做法一致，并通过patch改变万象中引用的词库名称，也就是不使用wanxiang.dict，可能是xxx.dict

**Comment by Mikachu2333** [comment]
> 这个是rime的设定，想要那样只能与文件夹引入dict的做法一致，并通过patch改变万象中引用的词库名称，也就是不使用wanxiang.dict，可能是xxx.dict

感谢告知！那我还是继续这么凑合过吧

```yaml
patch:
    translator/dictionary: custom_self
    radical_reverse_lookup/dictionary: custom_self
    user_dict_set/dictionary: custom_self
    add_user_dict/dictionary: custom_self
```
