### ISSUE TITLE
标准版 v8.0 build 始终出现error

### ISSUE THREAD

**Issue by Mikachu2333** [amzxyz/rime-wanxiang#121]
更新了正式版的8.0，还是炸

```log
E20250622 00:57:42.390748 13544 legacy_preset_config_plugin.cc:57] failed to include section default:punctuator
E20250622 00:57:42.391607 13544 config_component.cc:250] error building config: stroke.schema
```

---

部分自己的**关键配置**文件见此
[PART_self_config.zip](https://github.com/user-attachments/files/20846730/PART_self_config.zip)

**日志（最新）**
[logs.zip](https://github.com/user-attachments/files/20847572/logs.zip)

**Comment by Mikachu2333** [comment]
~~[rime.weasel.zip](https://github.com/user-attachments/files/20846616/rime.weasel.zip)~~
~~标准版：~~
~~1. 缺失 `wanxiang_lookup.dict.yaml` & `wanxiang_lookup.schema.yaml`~~

**Comment by Mikachu2333** [comment]
更新后再次测试，仍有error，再次上传相关文件如下，因为配置文件仅修正了一处个人设置的快捷键冲突问题（select_first_character与左中括号），故不再重复上传

[rime.weasel.zip](https://github.com/user-attachments/files/20846993/rime.weasel.zip)

**Comment by Mikachu2333** [comment]
更新了正式版的8.0，还是炸

```log
E20250622 00:57:42.390748 13544 legacy_preset_config_plugin.cc:57] failed to include section default:punctuator
E20250622 00:57:42.391607 13544 config_component.cc:250] error building config: stroke.schema
```

**Comment by Mikachu2333** [comment]
[logs.zip](https://github.com/user-attachments/files/20847572/logs.zip)

**Comment by Mikachu2333** [comment]
修改以下两个文件即可

default.custom.yaml
```yaml
patch:
  key_binder:
    bindings:
      - { accept: KP_0, send: 0, when: composing }
      - { accept: KP_1, send: 1, when: composing }
      - { accept: KP_2, send: 2, when: composing }
      - { accept: KP_3, send: 3, when: composing }
      - { accept: KP_4, send: 4, when: composing }
      - { accept: KP_5, send: 5, when: composing }
      - { accept: KP_6, send: 6, when: composing }
      - { accept: KP_7, send: 7, when: composing }
      - { accept: KP_8, send: 8, when: composing }
      - { accept: KP_9, send: 9, when: composing }
      - { accept: KP_Decimal, send: period, when: composing }
      - { accept: KP_Multiply, send: asterisk, when: composing }
      - { accept: KP_Add, send: plus, when: composing }
      - { accept: KP_Subtract, send: minus, when: composing }
      - { accept: KP_Divide, send: slash, when: composing }
      - { accept: KP_Enter, send: Return, when: composing }

  punctuator:
    __include: wanxiang_symbols:/symbol_table
```

wanxiang.custom.yaml
```yaml
patch:
  "key_binder/import_preset/=":
  key_binder/select_first_character: ""
  key_binder/select_last_character: ""
  "key_binder/bindings/+":
    - { accept: bracketleft, send: Page_Up, when: paging } # 使用中括号翻页
    - { accept: bracketright, send: Page_Down, when: has_menu }
```
