### ISSUE TITLE
用户自定义的固定词典，只支持带声调的拼音

### ISSUE THREAD

**Issue by Fortern** [amzxyz/rime-wanxiang#156]
用户自定义的固定词典，只支持带声调的拼音。

wanxiang.custom.yaml
```YAML
patch:
  translator/packs/+:
    - medical
```

medical.dict.yaml
```YAML
---
name: medical
version: "2025-01-31"
sort: by_weight
...
颞颧缝	niè quán fèng	1 # 使用这一行，存在这个词
# 颞颧缝	nie quan feng	1 # 使用这一行，没有这个词
```

用户可能会寻找一些专业领域词库，而这些词库大都不带声调。比如我找到的一些词库：
[fcitx5 pinyin moegirl 萌娘百科词库](https://github.com/outloudvi/mw2fcitx/wiki/fcitx5-pinyin-moegirl)
[中英医学词库](中英医学词库)

这使得用户导入第三方词库变得困难。

请问有什么解决方案吗？
